server:
  port: 8080

spring:
  application:
    name: openerp-bpmn-engine
    url: jdbc:h2:file:./h2/openbpm-engine-h2-database
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  # Настройки OpenBPM Engine
openbpm:
  bpm:
    admin-user.id: demo
    admin-user.password: demo
    auto-deployment-enabled: true
    deployment-resource-pattern: classpath*:*.bpmn, classpath*:*.form, classpath*:*.dmn